export function TermsOfService() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 md:px-8">
      <h1 className="text-3xl font-semibold tracking-tight text-gray-900 dark:text-white md:text-4xl">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
        Last updated: September 13, 2026
      </p>

      <div className="mt-10 space-y-8 text-gray-700 dark:text-gray-300">
        <section>
          <h2 className="text-xl font-medium text-gray-900 dark:text-white">
            Acceptance of Terms
          </h2>
          <p className="mt-3 leading-relaxed">
            These Terms of Service ("Terms") govern your use of the automated SMS
            services provided by Tavynq ("Tavynq," "we," "us," or "our"). By using our
            service, whether as a client business or as an end user who texts a phone
            number operated by Tavynq, you agree to these Terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-medium text-gray-900 dark:text-white">
            Description of Service
          </h2>
          <p className="mt-3 leading-relaxed">
            Tavynq provides automated SMS text messaging services on behalf of client
            businesses, including but not limited to HVAC, plumbing, and roofing
            companies. Our system uses artificial intelligence to respond to missed
            calls and inbound text messages in order to help client businesses
            communicate with, and schedule appointments for, their customers. Tavynq
            acts as a service provider to client businesses and is not itself the home
            service provider performing the underlying HVAC, plumbing, roofing, or other
            services.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-medium text-gray-900 dark:text-white">
            Message and Data Rates
          </h2>
          <p className="mt-3 leading-relaxed">
            Message and data rates may apply to text messages sent and received through
            this service. Message frequency varies based on your interactions with the
            client business. Standard rates from your wireless carrier apply. Reply
            STOP to opt out of messages at any time, or HELP for assistance.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-medium text-gray-900 dark:text-white">
            No Guarantee of Availability
          </h2>
          <p className="mt-3 leading-relaxed">
            While we strive to provide reliable, timely automated responses, we do not
            guarantee that the service will be uninterrupted, error-free, or available
            at all times. Automated responses are generated by AI and may not always
            perfectly reflect the intent of the client business or the end user.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-medium text-gray-900 dark:text-white">
            Limitation of Liability
          </h2>
          <p className="mt-3 leading-relaxed">
            To the fullest extent permitted by law, Tavynq and its officers, employees,
            and agents shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages, or any loss of profits, revenue, data,
            or business opportunities, arising out of or related to your use of, or
            inability to use, the service, including any actions taken or not taken by a
            client business in response to messages facilitated by our service. Our
            total liability for any claim arising out of these Terms or the service
            shall not exceed the amount paid by the applicable client business to
            Tavynq in the three (3) months preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-medium text-gray-900 dark:text-white">
            Client Business Responsibilities
          </h2>
          <p className="mt-3 leading-relaxed">
            Client businesses are responsible for ensuring they have appropriate consent
            to text their customers and for the accuracy of the information they provide
            to Tavynq for use in automated responses. Client businesses remain solely
            responsible for the services they perform for their own customers.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-medium text-gray-900 dark:text-white">
            Changes to These Terms
          </h2>
          <p className="mt-3 leading-relaxed">
            We may update these Terms from time to time. Continued use of the service
            after changes are posted constitutes acceptance of the revised Terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-medium text-gray-900 dark:text-white">
            Contact Us
          </h2>
          <p className="mt-3 leading-relaxed">
            If you have questions about these Terms, please contact us at{" "}
            <a href="mailto:hello@tavynq.com" className="underline underline-offset-2">
              hello@tavynq.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  )
}
